### Task01
Перепешите код, используя рекурсивный try.
### Task02
1. Создайте метод doSomething(), который может быть источником одного из типов checked exceptions (тело самого метода прописывать не обязательно).
2. Вызовите этот метод из main и обработайте в нем исключение, которое вызвал метод doSomething().
### Task03
1. Создайте класс Счетчик, у которого есть метод add(), увеличивающий значение внутренней int переменной на 1. 
2. Сделайте так, чтобы с объектом такого типа можно было работать в блоке try-with-resources. 
3. Нужно бросить исключение, если работа с объектом типа счетчик былане в ресурсном try  и/или ресурс остался открыт. Подумайте какой тип исключения подойдет лучше всего.
### Task04
1. Создайте класс исключения, который будет выбрасываться при делении на 0.
2. Исключение должно отображать понятное для пользователя сообщение об ошибке.
2. Создайте классисключений, которое будет возникать при обращении к 
3. Пустому элементу в массиве ссылочного типа. Исключение должно  отображать понятное для пользователя сообщение об ошибке.
4. Создайте класс исключения, которое будет возникать при попытке открыть несуществующий файл. Исключение должно отображать понятное для
пользователя сообщение об ошибке.
### Task05
1. Напишите метод,на вход которого подаётся двумерный строковый массив размером 4х4. При подаче массива другого размера необходимо бросить исключение MyArraySizeException.
2. Далее метод должен пройтись по всем элементам массива,преобразовать в int и просуммировать. 
3. Если в каком-то элементе массива преобразование не удалось (например, в ячейке лежит символ или текст вместо числа), должно быть брошено исключение MyArrayDataException с детализацией, в какой именно ячейке лежат неверные 
данные.
4. В методе main() вызвать полученный метод, обработать возможные исключения MyArraySizeException и MyArrayDataException и вывести
результат расчета (сумму элементов,при условии что подали на вход корректный массив).